[alias]
bd = "build --features dev"
rd = "run --features dev"
br = "build --release"
rr = "run --release"

[profile.release]
opt-level = 3
strip = true
codegen-units = 1
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
